import turtle
wn = turtle.Screen()
wn.setup(width=1100, height=600)
daniel = turtle.Turtle()
wn.bgcolor('LightBlue')
daniel.pensize(4)
daniel.color('red')
daniel.speed(7)

daniel.forward(70)
for i in range(13):
    daniel.forward(10)
    daniel.left(18)
daniel.left(40)
daniel.forward(60)

daniel.penup()
daniel.left(90)
daniel.forward(50)

daniel.pendown()
daniel.left(65)
daniel.forward(65)
daniel.right(150)
daniel.forward(65)
daniel.right(180)
daniel.forward(30)
daniel.left(90)
daniel.forward(25)

daniel.penup()
daniel.right(180)
daniel.forward(45)
daniel.pendown()

daniel.right(100)
daniel.forward(30)
daniel.left(180)
daniel.forward(60)
daniel.right(165)
daniel.forward(65)
daniel.left(165)
daniel.forward(65)

daniel.penup()
daniel.right(85)
daniel.forward(15)
daniel.right(90)
daniel.pendown()
daniel.forward(70)
daniel.right(180)
daniel.penup()
daniel.forward(90)
daniel.pendown()
daniel.forward(1)
daniel.penup()
daniel.right(180)
daniel.forward(40)

daniel.left(90)
daniel.forward(15)
daniel.pendown()
daniel.right(90)
daniel.forward(50)
daniel.right(180)
daniel.forward(75)
daniel.right(90)
daniel.forward(30)
daniel.left(180)
daniel.forward(30)
daniel.left(90)
daniel.forward(40)
daniel.left(90)
daniel.forward(30)
daniel.left(180)
daniel.forward(30)
daniel.left(90)
daniel.forward(30)
daniel.left(90)
daniel.forward(30)

daniel.penup()
daniel.forward(20)
daniel.left(90)
daniel.pendown()
daniel.forward(75)
daniel.left(180)
daniel.forward(80)
daniel.left(90)
daniel.forward(30)

wn.exitonclick()
